ALTER TABLE users
ADD COLUMN IF NOT EXISTS subjects JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS levels JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS onboarding_completed BOOLEAN DEFAULT FALSE;
