  {
    id: 'mobile',
    title: 'DarsakAI Student v1.3.0',
    description: 'تطبيق الهاتف للطلاب - متابعة الدرجات والحضور والاختبارات والملف الشخصي',
    descriptionEn: 'Student mobile app — grades, attendance, exams & profile',
    icon: Smartphone,
    color: '#00f3ff',
    files: [
      { name: 'DarsakAI-Student.apk', label: 'Android APK v1.3.0', size: '~80 MB' },
    ],
    platform: 'Android ✓',
    note: 'إصدار 1.3.0 • مساعد AI ذكي • Camera only permission',
  },
  {
    id: 'teacher',
    title: 'DarsakAI Teacher v1.2.0',
    description: 'تطبيق المدرس - مسح باركود للحضور بدون نظام PC',
    descriptionEn: 'Teacher mobile app — barcode attendance scanner without PC',
    icon: Monitor,
    color: '#FF6B00',
    files: [
      { name: 'DarsakAI-Teacher-v1.2.0.apk', label: 'Android APK (Teacher)', size: '~70 MB' },
    ],
    platform: 'Android ✓',
    note: 'إصدار 1.2.0 • Barcode Scanner • Sound Effects • Recurring Sessions • Login system',
  },
  {
    id: 'desktop',
    title: 'DarsakAI Desktop v2.0.0',
    description: 'نظام إدارة السنتر - طلاب، درجات، حضور، امتحانات، فواتير',
    descriptionEn: 'Learning center management — students, grades, attendance, exams',
    icon: Monitor,
    color: '#ccff00',
    files: [
      { name: 'DarsakAI-Setup-v2.0.0.exe', label: 'Windows Installer', size: '~15 MB' },
      { name: 'DarsakAI-Windows-v2.0.0.zip', label: 'Windows Portable (ZIP)', size: '~18 MB' },
    ],
    platform: 'Windows ✓',
    note: 'إصدار 2.0.0 • Offline-first • SQLite • Auto-sync • QR + PIN',
  },